version: "3.8"

services:
  server:
    image: hsn129/versusai-laravel:staging
    container_name: versusai-server
    restart: unless-stopped
    ports:
      - 8000:80
    env_file:
      - ./server/.env
    depends_on:
      - database
    command: ./dockerShell.sh

  database:
    image: mysql:8.0
    container_name: versusai-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./server/.env
    volumes:
      - db-data:/var/lib/mysql

  client:
    image: hsn129/versusai-nextjs:staging
    container_name: versusai-client
    restart: unless-stopped
    ports:
      - "80:3000"
    depends_on:
      - server

  realtime-server:
    image: hsn129/versusai-realtime:staging
    container_name: versusai-realtime
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - server

volumes:
  db-data:
