# name: Deploy VersusAI to EC2 (Staging)

on:
  push:
    branches:
      - main

jobs:
  build-and-push-laravel:
    name: Build & Push Laravel Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # github secrets
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Laravel Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/versusai-laravel:production ./server

      - name: Push Laravel Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/versusai-laravel:production
