# name: Deploy VersusAI to EC2 (Staging)

on:
  push:
    branches:
      - main

jobs:
  build-and-push-laravel:
    name: Build & Push Laravel Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
