# name: Deploy VersusAI to EC2 (Staging)

on:
  push:
    branches:
      - staging
jobs:
  build-and-push-laravel:
    name: Build & Push Laravel Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # github secrets
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Laravel Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/versusai-laravel:staging ./server

      - name: Push Laravel Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/versusai-laravel:staging

  build-and-push-realtime:
    name: Build & Push Realtime Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Realtime Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/versusai-realtime:staging ./realtime-server
      - name: Push Realtime Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/versusai-realtime:staging

  build-and-push-nextjs:
    name: Build & Push Next.js Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prepare client build
        working-directory: ./client
        run: |
          cat <<EOF > .env
          SOCKET_SERVER_URL=${{ secrets.SOCKET_SERVER_URL }}
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}
          EOF

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: ./client
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Next.js Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/versusai-nextjs:staging ./client

      - name: Push Next.js Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/versusai-nextjs:staging

  deploy-to-ec2:
    name: Deploy to EC2 (Staging)
    needs:
      [build-and-push-laravel, build-and-push-realtime, build-and-push-nextjs]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload docker-compose.yaml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.EC2_USER }}/versusai"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/versusai
            docker-compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/versusai-laravel:staging || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/versusai-realtime:staging || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/versusai-nextjs:staging || true
            docker-compose pull
            docker-compose up -d --remove-orphans
