name: Run Laravel & Next.js Tests for Staging

on:
  pull_request:
    branches:
      - staging

jobs:
  Laravel_Tests_Staging:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Laravel dependencies & run migrations
        working-directory: ./server
        run: |
          cp .env.testing .env
          composer install --prefer-dist --no-progress
          php artisan config:clear
          php artisan key:generate --env=testing
          php artisan migrate --env=testing

      - name: Run Laravel tests
        working-directory: ./server
        run: php artisan test

  NextJS_Tests_Staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run Next.js (React) tests
        working-directory: ./client
        run: npm test
